2020/12/30 02:20:32 : Error Connecting:HTTPConnectionPool(host='172.23.0.4', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5578a87b90>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2020/12/30 02:22:36 : Error Connecting:HTTPConnectionPool(host='172.23.0.4', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6d5a2edbd0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
